import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";
// import {
//   ClerkProvider,
//   SignInButton,
//   SignUpButton,
//   SignedIn,
//   SignedOut,
//   UserButton,
// } from '@clerk/nextjs'
import Header from "@/components/Header";
import FirstPage from "@/components/Home/FirstPage/FirstPage";

const inter = Montserrat({subsets: ['latin']})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Uber-C",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // <ClerkProvider>
  
      <html lang="en">
        {/* <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}> */}

        <body className={inter.className}>
          <Header />
          <div className=' w-screen h-screen'>
            <div className='w-[80%] h-screen  mx-auto '>
              <FirstPage />
            </div>
          </div>
          {children}
        </body>
      </html>
    
    // {/* </ClerkProvider> */}
  )
}
