import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import FirstPage from "@/components/FirstPage/FirstPage";
import Footer from "@/components/Footer";

const inter = Montserrat({subsets: ['latin']})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Uber-C",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
  
      <html lang="en">
        {/* <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}> */}

        <body className={inter.className}>
  
          {children}
        </body>
      </html>
    
  )
}
